baseURL = "https://svensmark.jp"
languageCode = "en-us"
paginate = 6
theme = "portio"
title = "Jens Svensmark"
# Main Menu
[[menu.main]]
name = "Home"
url = "#home"
weight = 1
[[menu.main]]
name = "About"
url = "#about"
weight = 2
# [[menu.main]]
# name = "Work"
# url = "#portfolio"
# weight = 4
[[menu.main]]
name = "Resume"
url = "#resume"
weight = 5
# [[menu.main]]
# name = "Blog"
# url = "#blog"
# weight = 6
[[menu.main]]
name = "Contact"
url = "#contact"
weight = 7

# Sitemap Menu
[[menu.sitemap]]
name = "About me"
url = "about"
weight = 1
# [[menu.sitemap]]
# name = "Latest Article"
# url = "#"
# weight = 4

[params]
blogPageURL = "blog"
contactLink = "contact"
copyright = "All right reserved copyright © Portio 2020. Built with Hugo and Netlify."
footerLogo = "images/contact/widget-logo.png"
# formspreeURL = "YOUR FORMSPREE URL"
# googleAnalytics = "YOUR GOOGLE ANALYTICS CODE"
logo = "images/site-navigation/logo.png"

[params.address]
email = "jens@svensmark.jp"

# Social icons
[[params.social]]
icon = "fa-linkedin-square"
url = "https://www.linkedin.com/in/jens-svensmark"
weight = 1
